### PR TITLE
Fix simple mixture docs

### PR DESCRIPTION
**Pull request by gregor-robinson**
# Citrine Python PR

## Description 
Updated simple mixture docs to reflect true parameters in SimpleMixturePredictor and IngredientsToSimpleMixturePredictor

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [x] I have bumped the version in setup.py

### CODE REVIEW

**Comment by latture** [comment]
The builds ran and passed, but the status still says pending. I'll trigger a rebuild.

**Comment by latture** [comment]
The build passed [again](https://travis-ci.org/github/CitrineInformatics/citrine-python/builds/691919539), but the status was never reported.

**Comment by latture** [comment]
@maxhutch Do you have any idea what's going on here? Status isn't getting reported from Travis CI after multiple rebuilds. Do you have permissions to merge?

**Comment by maxhutch** [comment]
Did you try turning it off and then turning it back on?

@latture you can also ask an admin to override the gate with a link to the passing build

**Pull request merged**
