### PR TITLE
[PLA-13742] Drop python 3.7.

### PR DESCRIPTION
**Pull request by anoto-moniz**
# Citrine Python PR

## Description 
It hit EOL in mid-2023.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Maintenance (non-breaking change to assist developers)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in __version\__.py

### CODE REVIEW

**Comment by anoto-moniz** [comment]
https://jenkins.corp.citrine.io/job/nextgen-ITs/43124/

**Comment by anoto-moniz** [comment]
https://jenkins.corp.citrine.io/job/nextgen-ITs/43126/

**Comment by anoto-moniz** [comment]
https://jenkins.corp.citrine.io/job/nextgen-ITs/43137/

**Comment by anoto-moniz** [comment]
nextgen IT runs:
- https://jenkins.corp.citrine.io/job/nextgen-ITs/43183/
- https://jenkins.corp.citrine.io/job/nextgen-ITs/43184/

**Review by kroenlein — APPROVED** [review]
To cross T's, have you checked 

https://docs.python.org/3/whatsnew/3.8.html

to see if dropping 3.7 support could clean up some code?

You are handling potential package upgrades elsewhere, so this looks good.

**Comment by anoto-moniz** [comment]
> To cross T's, have you checked
> 
> https://docs.python.org/3/whatsnew/3.8.html
> 
> to see if dropping 3.7 support could clean up some code?
> 
> You are handling potential package upgrades elsewhere, so this looks good.

I can't be certain due to the size of our codebase, but I can't think of many places the walrus operator or position-only arguments would be helpful. The f-string `=` will be great for debugging, but again, probably not in our code. As we made other updates to the code in 3.0 (or as I prep for 3.0), we can keep an eye out and upgrade as needed.

**Pull request merged**
