### PR TITLE
Docs/predictor report update

### PR DESCRIPTION
**Pull request by bfolie**
# Citrine Python PR

## Description 
Updates the documentation of the predictor report to reflect its current structure.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [X] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [X] I have bumped the version in setup.py

### CODE REVIEW

**Comment by bfolie** [comment]
> I'd like to circle back offline as to whether this is even a feature right now.

It is. I generated the example output by creating a predictor and running `project.predictors.get(predictor.uid).report`

**Comment by alexandraj777** [comment]
For context, part of the reason you're seeing this PR is because a recent retrospective on the Predictor Report Web UI project identified python client support and documentation for the Predictor Report API as a TODO. Here the [Predictor Report v1 Retrospective Action Items](https://docs.google.com/document/d/1VNfsB47hFaB80pOZxBuU3ZtwzQlQ8YM4IPvg4pem3Eg/edit?usp=sharing).

**Comment by andyczerwonka** [comment]
As per a discussion on Slack, we made no attempt to support the Predictor Report in the python client. This was an explicit decision - to defer. Supporting the Predictor Report, which was designed exclusively with the UI in mind, should probably be discussed in the context of the Python API, e.g. what use cases, how will it be used, etc.

**Comment by bfolie** [comment]
> As per a discussion on Slack, we made no attempt to support the Predictor Report in the python client. This was an explicit decision - to defer. Supporting the Predictor Report, which was designed exclusively with the UI in mind, should probably be discussed in the context of the Python API, e.g. what use cases, how will it be used, etc.

Understandable.
The feature is implemented and it's documented incorrectly, so something should be changed. Either we remove any mention of it from the documentation or we document it with an [Alpha] tag. My preference is to keep it, but I would be ok with removing it.

**Comment by bfolie** [comment]
Updating the `PredictorReport` object, then will reopen

**Pull request closed without merging**
