### PR TITLE
Pla 8867 python version test cov

### PR DESCRIPTION
**Pull request by talltea**
# Citrine Python PR

## Description 
Adds travis tests for python version 3.9, 3.10, and 3.11
Allows the 3.11 tests to fail 

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in setup.py

### CODE REVIEW

**Review by anoto-moniz — DISMISSED** [review]
LGTM

**Comment by anoto-moniz** [comment]
Bionic should also allow us to use 3.10 instead of the dev.

**Review by kroenlein — DISMISSED** [review]
Once tests pass, this will be great.  Let's cut a release! :D

**Review by anoto-moniz — APPROVED** [review]

**Comment by kroenlein** [comment]
Weird.  They have 3.6, 3.7, 3.8 etc., but no 3.10.  Only 3.10.0, 3.10.1, ...  Correcting.

**Review by kroenlein — DISMISSED** [review]

**Review by kroenlein — APPROVED** [review]
I had to push a substantial number of packages to much more current versions,

**Comment by kroenlein** [comment]
Tests were slow because it took 3.11-dev 13:45 to run, 11:56 of which was building pandas.  For the sake of developer velocity we may want to omit 3.11-dev until a 3.11 compatible pandas release.

**Comment by anoto-moniz** [comment]
> Tests were slow because it took 3.11-dev 13:45 to run, 11:56 of which was building pandas. For the sake of developer velocity we may want to omit 3.11-dev until a 3.11 compatible pandas release.

I'm in agreement with that. Also, do we normally start testing on Python dev releases? I'd have expected we'd at least wait until beta, if not until RC.

**Comment by kroenlein** [comment]
For the sake of posterity, please note this was closed in favor of PR is #713.

**Pull request closed without merging**
