### PR TITLE
Add test to codify expected behavior when uids is an empty dict

### PR DESCRIPTION
**Pull request by dekatzenel**
# Citrine Python PR

## Description 
Link replacement is surprisingly forgiving. Codify existing behavior when there is a empty uids dict so that we can decide if it's correct or not

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [x] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [x] I have bumped the version in setup.py

### CODE REVIEW

**Comment by asantas93** [comment]
The behavior I would expect is that you get a client-side exception as soon as you attempt to reference a GEMD object which does not have uids, e.g.

```python
spec = ProcessSpec('foo')
run = ProcessRun('bar', spec=spec)  # throws exception
```

I would expect the same behavior with the gemd version of the models as well, although I don't feel as strongly in that context.

**Comment by dekatzenel** [comment]
> The behavior I would expect is that you get a client-side exception as soon as you attempt to reference a GEMD object which does not have uids, e.g.
> 
> ```python
> spec = ProcessSpec('foo')
> run = ProcessRun('bar', spec=spec)  # throws exception
> ```
> 
> I would expect the same behavior with the gemd version of the models as well, although I don't feel as strongly in that context.

Note: citrine-python adds a CitrineId by default when instantiating an object, so the example above is using GEMD objects, at least for the spec.

That change feels like just enough work to be worth its own ticket, since we'd have to either implement the validation for every link manually or maybe do something clever in LinkOrElse

**Comment by asantas93** [comment]
> Note: citrine-python adds a CitrineId by default when instantiating an object, so the example above is using GEMD objects, at least for the spec.

IMO we should really NOT do this. The user should be forced to specify an external ID to link with manually if they want to use a data object which hasn't yet been written to the backend.

**Comment by maxhutch** [comment]
I'm not sure that I quite grok the test that this PR is adding.

Independently, if we're talking about changing the behavior of client-side links between objects, we should loop in @kroenlein and @EricLundberg

**Comment by dekatzenel** [comment]
> I'm not sure that I quite grok the test that this PR is adding.

It is testing what happens when both type and uids exist, and uids is an empty dict. The answer turns out to be that translation to uid doesn't happen.

**Comment by maxhutch** [comment]
> > I'm not sure that I quite grok the test that this PR is adding.
> 
> It is testing what happens when both type and uids exist, and uids is an empty dict. The answer turns out to be that translation to uid doesn't happen.

Gotcha.  Do we know why `replace_objects_with_links` is being used instead of [substitute_links](https://github.com/CitrineInformatics/gemd-python/blob/master/gemd/util/impl.py#L73) cc @bfolie ?

**Comment by bfolie** [comment]
> Gotcha. Do we know why `replace_objects_with_links` is being used instead of [substitute_links](https://github.com/CitrineInformatics/gemd-python/blob/master/gemd/util/impl.py#L73) cc @bfolie ?

I don't know. My recollection is that `replace_objects_with_links` was created to deal with some specific parts of serialization in the client, but isn't meant to be used by itself.

**Comment by dekatzenel** [comment]
That change appears to break e2e tests. Example:
```
___________________________________________________________________________ test_empirical_formula ___________________________________________________________________________

template_dataset = <citrine.resources.dataset.Dataset object at 0x7faddf546908>, dataset = <citrine.resources.dataset.Dataset object at 0x7fadb9e68ac8>

    def test_empirical_formula(template_dataset: Dataset, dataset: Dataset):
        proc = ProcessSpec(name='process')
    
        good_tmpl = PropertyTemplate(
            name='good_tmpl',
            bounds=CompositionBounds(components=['Na', 'Cl']),
        )
    
        good_prop_good_tmpl = PropertyAndConditions(
            Property(
                name='good_prop',
                value=EmpiricalFormula(formula='NaCl'),
                template=good_tmpl
            )
        )
    
        bad_tmpl = PropertyTemplate(
            name='bad_tmpl',
            bounds=CompositionBounds(components=['bad', 'tmpl']),
        )
    
        good_prop_bad_tmpl = PropertyAndConditions(
            Property(
                name=bad_tmpl.name,
                value=EmpiricalFormula(formula='NaCl'),
                template=bad_tmpl
            )
        )
    
        bad_prop_good_tmpl = PropertyAndConditions(
            Property(
                name='bad_formula',
                value=EmpiricalFormula(formula='garbage'),
                template=good_tmpl
            )
        )
    
        dataset.process_specs.register(proc)
        template_dataset.property_templates.register(good_tmpl)
        template_dataset.property_templates.register(bad_tmpl)
    
        with pytest.raises(BadRequest) as expt:
            dataset.material_specs.register(MaterialSpec(
                name='fail_bad_formula',
                properties=[bad_prop_good_tmpl],
                process=proc
            ))
>       expt_failure_id("empirical_formula.invalid", expt)

tests/strike-team-data/test_template_validation.py:303: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

id = 'empirical_formula.invalid', expt_info = <ExceptionInfo BadRequest tblen=5>

    def expt_failure_id(id, expt_info):
        bad_request: BadRequest = expt_info.value
>       return any(id in f.failure_id for f in bad_request.api_error.validation_errors)
E       AttributeError: 'NoneType' object has no attribute 'validation_errors'

tests/utils/__init__.py:17: AttributeError
----------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------
_session.py                118 ERROR    400 POST projects/84fc440a-a152-4cdb-8301-c86cb7797634/datasets/b25423d3-2702-455c-9088-32c5ed80655e/material-specs
_session.py                119 ERROR    The request content was malformed:
Parsed JSON values do not match with class constructor
args=fail_bad_formula,ProcessSpec(process,None,Set(),Set(),None,Uids(Set(CitrineId(183d753d-9eeb-415f-a3ec-a76c4bfaa726))),Set(),None,Set(),None,None),Set(PropertyAndConditions(Property(bad_formula,EmpiricalFormula(garbage),Some(PropertyTemplate(good_tmpl,CompositionBounds(Set(Cl, Na)),Uids(Set(CitrineId(5b9d394a-a23b-4735-9713-c83110ab562c))),None,Set(),None,None)),unknown,Set(),None),Set())),None,Uids(Set(CitrineId(a0bf63ce-1a56-407c-8953-3e7d474d55a6))),Set(),None,Set(),None,None
arg types=java.lang.String,io.citrine.faraday.api.model.objects.ProcessSpec,scala.collection.immutable.Set$Set1,scala.None$,io.citrine.faraday.api.model.Uids,scala.collection.immutable.Set$EmptySet$,scala.None$,scala.collection.immutable.Set$EmptySet$,scala.None$,scala.None$
executable=Executable(Constructor(public io.citrine.faraday.api.model.objects.MaterialSpec(java.lang.String,io.citrine.faraday.api.model.LinkOrElse,scala.collection.immutable.Set,scala.Option,io.citrine.faraday.api.model.Uids,scala.collection.immutable.Set,scala.Option,scala.collection.immutable.Set,scala.Option,scala.Option)))
cause=java.lang.ClassCastException@1c4e99c2
types comparison result=MATCH,io.citrine.faraday.api.model.objects.ProcessSpec(sun.misc.Launcher$AppClassLoader@18b4aac2) !<: io.citrine.faraday.api.model.LinkOrElse(sun.misc.Launcher$AppClassLoader@18b4aac2),MATCH,MATCH,MATCH,MATCH,MATCH,MATCH,MATCH,MATCH

```

**Comment by maxhutch** [comment]
The gemd-python `substitute_links` approach doesn't work because citrine-python overrides `as_dict` in a way that breaks it.  I'm sure we'll need to deal with that at some point, but it is not this day.  Tests pass both in repo and when this version is used with the e2e tests against development.

**Pull request merged**
