### PR TITLE
Add Predictors.convert_to_graph and Predictors.convert_and_update.

### PR DESCRIPTION
**Pull request by anoto-moniz**
https://citrine.atlassian.net/browse/PLA-8932

To aid in the transition away from SimpleML predictors. When called with
a SimpleML or Graph predictor, the equivalent Graph predictor will be
returned. Otherwise, the original predictor is returned.

# Citrine Python PR

## Description 
Please briefly explain the goal of the changes/this PR.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [X] I have added tests for 100% coverage
- [X] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [X] I have bumped the version in setup.py

### CODE REVIEW

**Comment by anoto-moniz** [comment]
Before merging, check with James and Andy to ensure the /convert endpoint is ready.

**Comment by dkao-citrine** [comment]
LGTM; just waiting for word on https://citrine.atlassian.net/browse/PLA-9010, as @anoto-moniz mentioned above.

**Comment by anoto-moniz** [comment]
> LGTM; just waiting for word on https://citrine.atlassian.net/browse/PLA-9010, as @anoto-moniz mentioned above.

Don't wait on that bug to approve this code; whether the SDK is ready for release is separate from whether we should release it.

That being said, there will be an update coming to this code (maybe later today?) to incorporate PLA-9071.

**Review by crleblanc — APPROVED** [review]
This looks like a straightforward change with good tests.  I see you need to resolve the conflict with __version__.py so you'll probably need another approval after that.

**Review by dkao-citrine — APPROVED** [review]

**Comment by anoto-moniz** [comment]
I noticed after posting that the actual error details were being suppressed due to a tweak I made to raising the `WorkflowConflictException` error. I need to update the appropriate test in `test_session`, then make the super small tweak, and then I'll update this PR.

**Review by crleblanc — APPROVED** [review]
LGTM

**Pull request merged**
