### PR TITLE
Formulation design space doc bugfix

### PR DESCRIPTION
**Pull request by eantono**
Added in the required `formulation_descriptor` argument to the `FormulationDesignSpace` constructor example.

# Citrine Python PR

## Description 
Please briefly explain the goal of the changes/this PR.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in setup.py

### CODE REVIEW

**Comment by talltea** [comment]
You're going to need to bump the version here: https://github.com/CitrineInformatics/citrine-python/blob/formulations-design-docs-edit/src/citrine/__version__.py#L1

**Review by kroenlein — CHANGES_REQUESTED** [review]
Even though this a just a doc fix, you'll need to increment the patch number in src/citrine/__version__.py

**Comment by eantono** [comment]
done!

**Review by talltea — DISMISSED** [review]
thanks for cleaning that up!

**Review by kroenlein — APPROVED** [review]
LGTM

**Review by kroenlein — DISMISSED** [review]
I updated the version following some drift in the main branch.  @eantono this should now be ready.

**Comment by eantono** [comment]
@kroenlein could i get another ✅  on the PR?

**Review by kroenlein — APPROVED** [review]

**Pull request merged**
