### PR TITLE
Rename Scorer to Score to match the API

### PR DESCRIPTION
**Pull request by sparadiso**
Update the name of the Scorer to Score to reflect the actual Orion API. This will be a breaking change for any tests/scripts that use the Score(r).

## Description 
Please briefly explain the goal of the changes/this PR.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.

### CODE REVIEW

**Comment by andrewmillspaugh** [comment]
Is the motivation just to match the api? Or did we have a product request for this?

**Comment by sparadiso** [comment]
It's just to match the API - I'm pulling @floparedes in

**Comment by floparedes** [comment]
API matching! thank you lgtm

**Comment by andrewmillspaugh** [comment]
:kanye-shrug:

**Pull request merged**
