### PR TITLE
Remove bounds from min/max objectives

### PR DESCRIPTION
**Pull request by maxhutch**
# Citrine Python PR

## Description 
These can be inferred from the descriptor; we don't need them to
be provided.  These classes are alpha.

### PR Type:
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [x] I have added tests for 100% coverage
- [x] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [x] I have bumped the version in setup.py

### CODE REVIEW

**Comment by latture** [comment]
When will we infer bounds if we remove them here? Maybe when a design workflow is run or will objectives require descriptors instead of keys?

**Comment by maxhutch** [comment]
> When will we infer bounds if we remove them here? Maybe when a design workflow is run or will objectives require descriptors instead of keys?

I was thinking in the design workflow run, where we can grab the descriptors from the predictor.

**Comment by latture** [comment]
> I was thinking in the design workflow run, where we can grab the descriptors from the predictor.

Did you want to do that before making this change or remove objective bounds entirely?

**Comment by maxhutch** [comment]
> Did you want to do that before making this change or remove objective bounds entirely?

No, since I think the overwhelming majority of users (if not the entirety) don't set these bounds, so applying them automatically would be a change to default behavior.  I brought it up more to indicate that we don't need to collect the information here **even if** want to set these bounds in the default case.

**Review by latture — DISMISSED** [review]

**Review by latture — APPROVED** [review]

**Pull request merged**
