### PR TITLE
Cleanup Teams deprecation warning.

### PR DESCRIPTION
**Pull request by anoto-moniz**
Combines the v1_deprecation_warning decorator into the use_teams
decorator. Updates the base message string: remove large space, change
"Team's" to "Teams", specify the method will be unavailable once Teams
is released.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Maintenance (non-breaking change to assist developers)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [X] I have communicated the downstream consequences of the PR to others.
- [X] I have bumped the version in setup.py

### CODE REVIEW

**Review by kroenlein — COMMENTED** [review]
Can we add some tests?  Other than that, looks good.

**Comment by anoto-moniz** [comment]
> Can we add some tests? Other than that, looks good.

@kroenlein I took a look and confirmed that tests are already in place from previous PRs. Which makes sense, since the changes in this one just adjusts the wording and code.

I do need to figure out why the tests failed. I see one specific error (which didn't show up locally?) which I'll push up a fix for, and take it from there.

**Comment by anoto-moniz** [comment]
The builds are failing when trying to pip install the setup.py. I haven't made any changes to it, and I have updated `__version__.py`, so I'm unclear why. There's no rebuild button on Travis (at least that I can see), so I'm gonna do a small cleanup push and see if that fixes it.

**Review by jspeerless — APPROVED** [review]
LGTM!

**Pull request merged**
