### PR TITLE
Update string formatting of delete dataset contents confirmation prompt

### PR DESCRIPTION
**Pull request by xperrylinn**
Suggested update to the string formatting of delete dataset contents confirmation prompt to include name as well. Name is more readable and memorizable then UUID which makes it easier to recall if that's the dataset you want to delete.

cc @sdedkins 

# Citrine Python PR

## Description 
Please briefly explain the goal of the changes/this PR.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in setup.py

### CODE REVIEW

**Review by kroenlein — DISMISSED** [review]
I have minor concerns about the line length on this, but the motivation tracks.

**Comment by kroenlein** [comment]
```
$ flake8 src

src/citrine/resources/dataset.py:285:100: E501 line too long (120 > 99 characters)

The command "flake8 src" exited with 1.
```
This is different than the concern about length of the printed line.  The formatted string needs to be broken across to lines of the source file.

**Comment by xperrylinn** [comment]
@kroenlein - I removed some text from the formatted string to make it more compact and added a newline to comply with flake8

**Review by kroenlein — APPROVED** [review]
LGTM!

**Review by kroenlein — APPROVED** [review]

**Pull request merged**
