### PR TITLE
PLA-7736: better timeout error messages

### PR DESCRIPTION
**Pull request by dkao-citrine**
[PLA-7736](https://citrine.atlassian.net/browse/PLA-7736)

## Description 
Many of the heartbeat test failures we're seeing are caused by end-to-end tests timing out during design executions with this terse error message:

```
14:08:06  __________________ test_watercolor_data_source_design_results __________________
14:08:06  [gw1] linux -- Python 3.6.13 /usr/local/bin/python
14:08:06  tests/orion/test_watercolor_design.py:22: in test_watercolor_data_source_design_results
14:08:06      timeout=ORION_EXECUTION_TIMEOUT
14:08:06  /usr/local/lib/python3.6/site-packages/citrine/jobs/waiting.py:163: in wait_while_executing
14:08:06      interval=interval)
14:08:06  /usr/local/lib/python3.6/site-packages/citrine/jobs/waiting.py:76: in wait_for_asynchronous_object
14:08:06      raise ConditionTimeoutError("Timeout reached, but task is still in progress")
14:08:06  E   citrine.jobs.waiting.ConditionTimeoutError: Timeout reached, but task is still in progress
```

This pull request takes the first step toward transparency by exposing the design execution ID, the exact object that is timing out.  More work is forthcoming that will log design execution data to DataDog for better tracking and easier debugging.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [x] I have added tests for 100% coverage
- [x] I have written Numpy-style docstrings for every method and class. (Not necessary -- I just modified an existing class.)
- [x] I have communicated the downstream consequences of the PR to others.
- [x] I have bumped the version in setup.py

### CODE REVIEW

**Comment by dkao-citrine** [comment]
Looking into failing CI tests now.

**Comment by dkao-citrine** [comment]
I exceeded the line length of 100 characters in two places. Fixed now.

**Comment by dkao-citrine** [comment]
Hm, more failures. I'm moving this into draft mode until I can resolve it.

**Comment by dkao-citrine** [comment]
Looks like another linting error. Hopefully this last commit fixed it.

**Review by fayvor — APPROVED** [review]
lgtm.

**Pull request merged**
