### PR TITLE
PLA-7230 remove legacy workflow registration/update/trigger

### PR DESCRIPTION
**Pull request by talltea**
# Citrine Python PR

## Description 
**Do not merge - nextgen devkit e2es will fail**
Overriding the register, update and trigger methods to raise NotImplemented errors (the collections were alpha and have been deprecated since at least version `0.101.0`)

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in setup.py

### CODE REVIEW

**Comment by talltea** [comment]
I'm running this against [the devkit changes](https://github.com/CitrineInformatics/nextgen-devkit/pull/872) here https://jenkins.corp.citrine.io/job/Devkit-custom/528/ but it's taking for ever to start the job

**Comment by bfolie** [comment]
Why do this instead of removing the collections entirely? Is it for better user-messaging?

**Comment by talltea** [comment]
> Why do this instead of removing the collections entirely? Is it for better user-messaging?

We want to leave the ability to read existing modules for now, just remove the ability to update/register, and the Errors are for user feedback

**Review by bfolie — DISMISSED** [review]

**Review by bfolie — APPROVED** [review]

**Comment by talltea** [comment]
successful build here: https://jenkins.corp.citrine.io/job/Devkit-custom/531/
version bumped

**Review by bfolie — APPROVED** [review]

**Pull request merged**
