### PR TITLE
Migrate Travis secrets to project settings

### PR DESCRIPTION
**Pull request by teekennedy**
# Citrine Python PR

## Description 

The existing access token used to publish citrine-python's docs to GitHub Pages
has been revoked. I've generated a new token under the `jenkins-citrine` user,
and saved it to the [project settings for citrine-python](https://app.travis-ci.com/github/CitrineInformatics/citrine-python/settings) in Travis.

Because the settings page shows us the variable name for the secret, and
updating a secret doesn't require a PR. I'm removing the encrypted variables
from `.travis.yml` in favor of managing them through the project settings.

### PR Type:
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Adherence to team decisions
- [ ] I have added tests for 100% coverage
- [ ] I have written Numpy-style docstrings for every method and class.
- [ ] I have communicated the downstream consequences of the PR to others.
- [ ] I have bumped the version in setup.py

### CODE REVIEW

**Review by jfriend-citrine — APPROVED** [review]
excellent!

**Review by talltea — APPROVED** [review]
👍

**Review by kroenlein — DISMISSED** [review]
LGTM

**Comment by talltea** [comment]
oh the version bump 😞

**Review by kroenlein — APPROVED** [review]
Looks even better!

**Pull request merged**
